version: '3.8'

services:
  dev-db:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-backend

  redis: 
    image: redis:7.0
    restart: always
    ports: 
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks: 
      - chat-backend

  redisinsight:
    image: redis/redisinsight:2.68
    container_name: redisinsight
    restart: always
    ports:
      - "${REDISINSIGHT_PORT}:5540"
    networks:
      - chat-backend

volumes:
  postgres_data:
  redis_data:

networks:
  chat-backend:
